"""empty message

Revision ID: 14be20713deb
Revises: 
Create Date: 2025-08-06 16:13:52.798865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14be20713deb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_songs', schema=None) as batch_op:
        batch_op.drop_column('release_date')
        batch_op.drop_column('duration')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
